/**
 * pages/admin/students.html controller.
 * Full CRUD reference implementation: server-driven list + search +
 * filters + pagination, create/edit via modal form, deactivate via
 * confirmation dialog. Role-aware: only users permitted to manage
 * students see the "Add Student" action.
 */
(function () {
  'use strict';

  let classesCache = [];
  let table = null;

  function classOptionsHtml(selectedId) {
    return classesCache
      .map((c) => `<option value="${escapeHtml(c.id)}" ${String(c.id) === String(selectedId) ? 'selected' : ''}>${escapeHtml(c.name || c.level)}</option>`)
      .join('');
  }

  function armOptionsHtml(arms, selectedId) {
    return (arms || [])
      .map((a) => `<option value="${escapeHtml(a.id)}" ${String(a.id) === String(selectedId) ? 'selected' : ''}>${escapeHtml(a.name)}</option>`)
      .join('');
  }

  async function loadClassesIntoFilter() {
    const filterSelect = document.getElementById('filter-class');
    try {
      const { items } = await ClassesService.list({ pageSize: 100 });
      classesCache = items;
      if (filterSelect) {
        filterSelect.innerHTML = `<option value="">All Classes</option>${classOptionsHtml('')}`;
      }
    } catch (err) {
      Toast.error('Unable to load classes for filtering.');
    }
  }

  function studentFormHtml(student) {
    const s = student || {};
    return `
      <form id="student-form" novalidate>
        <div class="form-section-title">Personal Information</div>
        <div class="form-row">
          <div class="form-group">
            <label class="form-label">First Name <span class="required">*</span></label>
            <input type="text" name="firstName" value="${escapeHtml(s.firstName || '')}" required />
            <span class="form-error"></span>
          </div>
          <div class="form-group">
            <label class="form-label">Last Name <span class="required">*</span></label>
            <input type="text" name="lastName" value="${escapeHtml(s.lastName || '')}" required />
            <span class="form-error"></span>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group">
            <label class="form-label">Date of Birth</label>
            <input type="date" name="dateOfBirth" value="${escapeHtml(toInputDate(s.dateOfBirth) || '')}" />
          </div>
          <div class="form-group">
            <label class="form-label">Gender</label>
            <select name="gender">
              <option value="">Select…</option>
              <option value="MALE" ${s.gender === 'MALE' ? 'selected' : ''}>Male</option>
              <option value="FEMALE" ${s.gender === 'FEMALE' ? 'selected' : ''}>Female</option>
            </select>
          </div>
        </div>

        <div class="form-section-title">Academic Information</div>
        <div class="form-row">
          <div class="form-group">
            <label class="form-label">Class <span class="required">*</span></label>
            <select name="classId" id="student-class-select" required>
              <option value="">Select class…</option>
              ${classOptionsHtml(s.classId)}
            </select>
            <span class="form-error"></span>
          </div>
          <div class="form-group">
            <label class="form-label">Class Arm</label>
            <select name="classArmId" id="student-arm-select">
              <option value="">Select arm…</option>
            </select>
          </div>
        </div>
        ${
          s.regNumber
            ? `<div class="form-group"><label class="form-label">Registration Number</label><input type="text" value="${escapeHtml(s.regNumber)}" disabled /><span class="form-help">Auto-generated by the system.</span></div>`
            : ''
        }

        <div class="form-section-title">Contact & Parent Information</div>
        <div class="form-row">
          <div class="form-group">
            <label class="form-label">Email</label>
            <input type="email" name="email" value="${escapeHtml(s.email || '')}" />
          </div>
          <div class="form-group">
            <label class="form-label">Phone Number</label>
            <input type="text" name="phone" value="${escapeHtml(s.phone || '')}" />
            <span class="form-help">Phone numbers are not required to be unique.</span>
          </div>
        </div>
        <div class="form-group">
          <label class="form-label">Address</label>
          <textarea name="address">${escapeHtml(s.address || '')}</textarea>
        </div>
      </form>
    `;
  }

  async function populateArmsForClass(classSelect, armSelect, selectedArmId) {
    const classId = classSelect.value;
    armSelect.innerHTML = '<option value="">Loading arms…</option>';
    armSelect.disabled = true;
    if (!classId) {
      armSelect.innerHTML = '<option value="">Select a class first</option>';
      return;
    }
    try {
      const { items } = await ClassesService.arms(classId);
      armSelect.innerHTML = `<option value="">Select arm…</option>${armOptionsHtml(items, selectedArmId)}`;
    } catch (err) {
      armSelect.innerHTML = '<option value="">Unable to load arms</option>';
    } finally {
      armSelect.disabled = false;
    }
  }

  function openStudentModal(student) {
    const isEdit = Boolean(student && student.id);
    Modal.open({
      title: isEdit ? 'Edit Student' : 'Add Student',
      description: isEdit ? `Editing ${student.firstName} ${student.lastName}` : 'Enter the new student\u2019s details.',
      size: 'lg',
      bodyHtml: studentFormHtml(student),
      footerHtml: `
        <button type="button" class="btn btn-secondary" data-action="cancel">Cancel</button>
        <button type="submit" form="student-form" class="btn btn-primary" id="student-save-btn">${isEdit ? 'Save Changes' : 'Add Student'}</button>
      `,
      onMount: async (modalEl) => {
        modalEl.querySelector('[data-action="cancel"]').addEventListener('click', Modal.close);

        const classSelect = modalEl.querySelector('#student-class-select');
        const armSelect = modalEl.querySelector('#student-arm-select');
        if (classSelect.value) await populateArmsForClass(classSelect, armSelect, student && student.classArmId);
        classSelect.addEventListener('change', () => populateArmsForClass(classSelect, armSelect));

        const form = modalEl.querySelector('#student-form');
        form.addEventListener('submit', async (e) => {
          e.preventDefault();
          const formData = new FormData(form);
          const values = Object.fromEntries(formData.entries());

          const { valid, errors } = Validators.validateForm(values, {
            firstName: [(v) => Validators.required(v, 'First name')],
            lastName: [(v) => Validators.required(v, 'Last name')],
            classId: [(v) => Validators.required(v, 'Class')],
            email: [(v) => Validators.email(v)],
            phone: [(v) => Validators.phone(v)],
          });

          form.querySelectorAll('.form-group').forEach((g) => g.classList.remove('has-error'));
          if (!valid) {
            Object.entries(errors).forEach(([field, message]) => {
              const input = form.querySelector(`[name="${field}"]`);
              const group = input && input.closest('.form-group');
              if (group) {
                group.classList.add('has-error');
                const err = group.querySelector('.form-error');
                if (err) err.textContent = message;
              }
            });
            return;
          }

          const saveBtn = document.getElementById('student-save-btn');
          Loader.setButtonLoading(saveBtn, true, isEdit ? 'Saving…' : 'Adding…');
          try {
            if (isEdit) {
              await StudentsService.update(student.id, values);
              Toast.success('Student updated successfully.');
            } else {
              await StudentsService.create(values);
              Toast.success('Student added successfully.');
            }
            Modal.close();
            table.reload();
          } catch (err) {
            Toast.error(err.message || 'Unable to save this student.');
          } finally {
            Loader.setButtonLoading(saveBtn, false);
          }
        });
      },
    });
  }

  function openDeactivateConfirm(student) {
    ConfirmDialog.open({
      title: 'Deactivate Student',
      message: `Are you sure you want to deactivate ${student.firstName} ${student.lastName} (${student.regNumber || 'no reg. no.'})? They will lose access to the portal.`,
      confirmLabel: 'Deactivate',
      tone: 'danger',
      onConfirm: async () => {
        await StudentsService.deactivate(student.id);
        Toast.success('Student deactivated.');
        table.reload();
      },
    });
  }

  function rowActionsHtml(row) {
    const canManage = Permissions.canAccessModule(window.CurrentUser.role, 'students');
    return `
      <div class="row" style="gap:4px; justify-content:flex-end;">
        <a class="icon-link" href="student-details.html?id=${encodeURIComponent(row.id)}" title="View">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75"><circle cx="12" cy="12" r="3"/><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z"/></svg>
        </a>
        ${
          canManage
            ? `
        <button type="button" class="icon-link" data-action="edit" title="Edit">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75"><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4Z"/></svg>
        </button>
        <button type="button" class="icon-link" data-action="deactivate" title="Deactivate">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75"><circle cx="12" cy="12" r="9"/><path d="M8 8l8 8"/></svg>
        </button>`
            : ''
        }
      </div>
    `;
  }

  document.addEventListener('DOMContentLoaded', async () => {
    const tbody = document.getElementById('students-tbody');
    const paginationEl = document.getElementById('students-pagination');
    const searchInput = document.getElementById('students-search');
    const filterClass = document.getElementById('filter-class');
    const filterStatus = document.getElementById('filter-status');
    const addBtn = document.getElementById('add-student-btn');

    if (!window.CurrentUser) return;
    const canManage = Permissions.canAccessModule(window.CurrentUser.role, 'students');
    if (addBtn) addBtn.hidden = !canManage;

    await loadClassesIntoFilter();

    table = DataTable.create({
      tbody,
      paginationEl,
      columns: [
        {
          key: 'name',
          label: 'Student',
          render: (row) => `
            <div class="avatar-cell">
              <span class="avatar">${escapeHtml(initials(`${row.firstName || ''} ${row.lastName || ''}`))}</span>
              <div>
                <div class="name">${escapeHtml(`${row.firstName || ''} ${row.lastName || ''}`)}</div>
                <div class="sub">${escapeHtml(row.regNumber || '—')}</div>
              </div>
            </div>`,
        },
        { key: 'className', label: 'Class', render: (row) => escapeHtml(row.className || row.class?.name || '—') },
        { key: 'classArmName', label: 'Arm', render: (row) => escapeHtml(row.classArmName || row.classArm?.name || '—') },
        { key: 'email', label: 'Email', render: (row) => escapeHtml(row.email || '—') },
        { key: 'phone', label: 'Phone', render: (row) => escapeHtml(row.phone || '—') },
        { key: 'status', label: 'Status', render: (row) => `<span class="badge ${statusBadgeClass(row.status)}">${escapeHtml(titleCaseFromEnum(row.status))}</span>` },
      ],
      rowActions: rowActionsHtml,
      fetchPage: (page, filters) => StudentsService.list({ page, pageSize: 20, ...filters }),
      emptyMessage: 'No students found.',
      emptyActionHtml: canManage ? '<button type="button" class="btn btn-primary btn-sm" data-action="empty-add">Add Student</button>' : '',
    });

    table.load();

    tbody.addEventListener('click', async (e) => {
      const row = e.target.closest('tr[data-row-id]');
      const emptyAdd = e.target.closest('[data-action="empty-add"]');
      if (emptyAdd) {
        openStudentModal(null);
        return;
      }
      if (!row) return;
      const id = row.dataset.rowId;

      if (e.target.closest('[data-action="edit"]')) {
        try {
          const student = await StudentsService.get(id);
          openStudentModal(student);
        } catch (err) {
          Toast.error(err.message || 'Unable to load student details.');
        }
      } else if (e.target.closest('[data-action="deactivate"]')) {
        try {
          const student = await StudentsService.get(id);
          openDeactivateConfirm(student);
        } catch (err) {
          Toast.error(err.message || 'Unable to load student details.');
        }
      }
    });

    if (addBtn) addBtn.addEventListener('click', () => openStudentModal(null));

    const applyFilters = debounce(() => {
      table.setFilters({
        search: searchInput.value.trim(),
        classId: filterClass.value,
        status: filterStatus.value,
      });
    }, 350);

    searchInput.addEventListener('input', applyFilters);
    filterClass.addEventListener('change', applyFilters);
    filterStatus.addEventListener('change', applyFilters);
  });
})();
